### ISSUE TITLE
Antenna characteristics

### ISSUE THREAD

**Issue by vigneshrk29** [EMFMed/MERIT#3]
Hello, 

Thanks for the code. I would like to enquire if antenna characteristics (antenna delay) are taken into account? 
Also, is there a possibility to only evaluate the data in 2d instead of 3d ( measurements taken at a fixed height)?

Thanks,
Vignesh

**Comment by shahkaram** [comment]
Hello dear Vignesh,

1- No, I don't think so.

2- Yes, it's possible. 
**If you mean you have 2-D antenna structure:** please check "antenna_locations" that is the locations of each antenna. If you have your own data, so you need to make the "antenna_locations" by yourself. Please note that you have to set z-value even you have 2-D antenna structure (all z-values are the same). Then, "channel_names" indicates for each signal, which antenna is the transmitter and which one is the receiver (as the index of the antennas in "antenna_locations" list).
**If you want to reconstruct 2-D image:** 2-D or 3-D antenna array makes no difference. You can reconstruct only one slice. Please check the values of "points" and "axes_" which makes in the line 70. The "points" are the points in which the beamformer estimates the scattered energy. The structure is easy, each point has 3 values; x,y, and z. But about "axes_", I can't remember the exact type or structure, but it contains the values in each axis; 3 sets for x-values, y-values, and z-values. 
You can use line 70, then remove unwanted points from "points" and corresponding z-values from "axes_". Or., make them by yourself.

To see the result, just modify the most last number in the line 87.

Please feel free to ask any question.

**Comment by declanol** [comment]
1) Correct, the example codes require that the signals originate from the points in antenna locations. This can be achieved in a number of ways, the antenna locations can be the virtual antenna locations, by adding extra delay to times calculated by MERIT or by other forms of calibration. Which you would use would depend on the exact hardware set-up, there is no universal method.

**Comment by vigneshrk29** [comment]
Thank you shahkaram and declanol for your replies. I shall try running the code again by setting a fixed value of z. 
I shall try adding a time delay based on the antenna being used to evaluate whether the result varies. I asked since some papers suggest that the location of scatterers would be incorrect if we do not take into account receiving and transmitting delays of the antennas while calculating the intensity of backscattered signals from a point
